//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageProcessing.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class MarkSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MarkSettings defaultInstance = ((MarkSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MarkSettings())));
        
        public static MarkSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color MarkColor {
            get {
                return ((global::System.Drawing.Color)(this["MarkColor"]));
            }
            set {
                this["MarkColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public byte MarkLength {
            get {
                return ((byte)(this["MarkLength"]));
            }
            set {
                this["MarkLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte MarkLinewidth {
            get {
                return ((byte)(this["MarkLinewidth"]));
            }
            set {
                this["MarkLinewidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color ChooseMarkColor {
            get {
                return ((global::System.Drawing.Color)(this["ChooseMarkColor"]));
            }
            set {
                this["ChooseMarkColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public byte ChooseMarkLength {
            get {
                return ((byte)(this["ChooseMarkLength"]));
            }
            set {
                this["ChooseMarkLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte ChooseMarkLinewidth {
            get {
                return ((byte)(this["ChooseMarkLinewidth"]));
            }
            set {
                this["ChooseMarkLinewidth"] = value;
            }
        }
    }
}
